# Generated by Django 5.2.7 on 2025-10-10 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(help_text='Person who brought the device', max_length=255)),
                ('hardware_type', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('nature_of_complaint', models.TextField()),
                ('maintenance_action_taken', models.TextField(blank=True, null=True)),
                ('department_email', models.EmailField(max_length=254)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition_after_repair', models.CharField(blank=True, choices=[('satisfactory', 'Satisfactory'), ('unsatisfactory', 'Unsatisfactory')], help_text='To be filled by department after repair', max_length=20, null=True)),
                ('signature', models.CharField(blank=True, help_text='Filled by department', max_length=255, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ict_personnel', models.ForeignKey(blank=True, help_text='Logged-in ICT staff handling this repair', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repair Record',
                'verbose_name_plural': 'Repair Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
